# Generated by Django 5.0.2 on 2024-03-27 11:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.PositiveSmallIntegerField()),
                ('uuid', models.UUIDField(unique=True)),
                ('model', models.TextField()),
                ('speed', models.CharField(choices=[('SLOW', 'SLOW'), ('NORMAL', 'NORMAL'), ('FAST', 'FAST')], default='NORMAL', max_length=50)),
                ('util', models.PositiveSmallIntegerField()),
                ('is_running_amumax', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('RUNNING', 'RUNNING'), ('PENDING', 'PENDING'), ('RESERVED', 'RESERVED'), ('UNAVAILABLE', 'UNAVAILABLE')], default='PENDING', max_length=50)),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('name', models.CharField(max_length=15, unique=True)),
                ('number_of_gpus', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('RESERVED', 'RESERVED'), ('UNAVAILABLE', 'UNAVAILABLE')], default='PENDING', max_length=50)),
                ('connection_status', models.CharField(choices=[('CONNECTED', 'CONNECTED'), ('DISCONNECTED', 'DISCONNECTED')], default='CONNECTED', max_length=50)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concurrent_jobs', models.SmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19')], default=10)),
                ('auth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('submit_time', models.DateTimeField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('error_time', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('LOW', 'LOW'), ('NORMAL', 'NORMAL'), ('HIGH', 'HIGH')], default='NORMAL', max_length=6)),
                ('gpu_partition', models.CharField(choices=[('SLOW', 'SLOW'), ('NORMAL', 'NORMAL'), ('FAST', 'FAST'), ('UNDEF', 'UNDEF')], default='NORMAL', max_length=6)),
                ('duration', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('FINISHED', 'FINISHED'), ('INTERRUPTED', 'INTERRUPTED'), ('RUNNING', 'RUNNING')], default='PENDING', max_length=50)),
                ('output', models.TextField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('flags', models.CharField(blank=True, max_length=150, null=True)),
                ('gpu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job', to='manager.gpu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.customuser')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='node', to='manager.node')),
            ],
        ),
        migrations.AddField(
            model_name='gpu',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.node'),
        ),
    ]
