dev:
	podman network create --ignore amuman-dev
	podman run --rm -it --replace --tz local --pull newer \
		--name amuman-frontend-dev \
		--network amuman-dev \
		-p 3000:3000 \
		-v ./..:/app \
		-w /app/frontend \
		docker.io/node:21 bash

staging:
	podman network create --ignore amuman-staging
	podman run --rm -it --replace --tz local --pull newer \
		--name amuman-frontend-staging \
		--network amuman-staging \
		-v ./..:/app \
		-w /app/frontend \
		docker.io/node:21 bash 
