

[tool.ruff.lint]
ignore = ["E501","RUF012"]
select = [
    # pycodestyle
    "E",
    "W",
    "C90",
    "N",
    # "PL",
    "ARG",
    "RUF",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]

