"""
Django settings for amuman project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
from datetime import timedelta
from pathlib import Path
from .settings import *

INSTALLED_APPS += [
    "manager",
]

URL_MODE_PREFIX = 'manager'  # Prefiks URL dla trybu klienta
DATABASES.update({
    'default': {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "managerdb.sqlite3", 
    }
})

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'manager/static'),
]