FROM docker.io/python:3.11-slim

RUN DEBIAN_FRONTEND="noninteractive" apt-get update && apt-get install -y --no-install-recommends \
    redis-server \
    git && \
    pip install --upgrade pip

ENV SECRET_KEY=
ENV DJANGO_SUPERUSER_EMAIL=
ENV DJANGO_SUPERUSER_USERNAME=
ENV DJANGO_SUPERUSER_PASSWORD=
ENV DOMAIN_URL=
ENV DEBUG=FALSE

WORKDIR /app/manager
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .
ENV SMB_MOUNT_POINT=/mnt/smb
CMD redis-server /etc/redis/redis.conf \
    && ./manage.py makemigrations manager \
    && ./manage.py migrate manager \ 
    && ./manage.py makemigrations \
    && ./manage.py migrate \
    && ./manage.py createsuperuser --noinput \
    && ./manage.py runserver 0.0.0.0:8000
