FROM docker.io/ubuntu:22.04

ARG DEBIAN_FRONTEND="noninteractive"
ARG PYTHON_VER=3.11
RUN apt-get update && apt-get install -y --no-install-recommends \
    bash \
    bash-completion \
    ca-certificates \
    curl \
    git \
    cifs-utils \
    redis-server \
    python${PYTHON_VER} python${PYTHON_VER}-dev python3-pip python-is-python3 && \
    pip install --upgrade pip &&\
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*



ENV SECRET_KEY=
ENV DJANGO_SUPERUSER_EMAIL=
ENV DJANGO_SUPERUSER_USERNAME=
ENV DJANGO_SUPERUSER_PASSWORD=
ENV SMB_USER=
ENV SMB_PASSWORD=
ENV SMB_URL=


WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .
ENV SMB_MOUNT_POINT=/mnt/smb
CMD mkdir -p ${SMB_MOUNT_POINT} \
    && mount -t cifs -o username=${SMB_USER},password=${SMB_PASSWORD},uid=1000,gid=1000 ${SMB_URL} ${SMB_MOUNT_POINT} \
    && redis-server /etc/redis/redis.conf \
    && python manage.py makemigrations manager \
    && python manage.py migrate manager \ 
    && python manage.py makemigrations \
    && python manage.py migrate \
    && python manage.py createsuperuser --noinput \
    && python manage.py runserver 0.0.0.0:8000
