build:
	podman build . -t amuman

build_db:
	podman run --rm -it -v .:/app amuman poetry run python manage.py makemigrations 
	podman run --rm -it -v .:/app amuman poetry run python manage.py migrate --settings=amuman.settings_manager

run: 
	podman run --rm -it -v .:/app -p 8000:8000 amuman
