docker_build:
	podman build . -t amuman

docker_build_db:
	podman run --rm -it -v .:/app -p 8000:8000 amuman poetry run python manage.py makemigrations 
	podman run --rm -it -v .:/app -p 8000:8000 amuman poetry run python manage.py migrate --settings=amuman.settings_manager

docker_run:
	podman run --rm -it -v .:/app -p 8000:8000 amuman
