# Generated by Django 4.2.9 on 2024-01-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Local",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("node_id", models.CharField(max_length=15, unique=True)),
                (
                    "managerNmUrl",
                    models.CharField(
                        default="http://localhost:8000/manager/node-management/",
                        max_length=15,
                    ),
                ),
                (
                    "managerWsUrl",
                    models.CharField(
                        default="ws://localhost:8000/ws/node/", max_length=15
                    ),
                ),
            ],
        ),
    ]
