# Generated by Django 4.2.9 on 2024-01-25 22:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("node", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="local",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
