# Generated by Django 4.2.9 on 2024-01-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("node", "0002_alter_local_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="local",
            name="url",
            field=models.CharField(
                default="http://localhost:8000/manager/node-management/", max_length=15
            ),
        ),
    ]
