dev cmd="None":
	podman network create --ignore amuman-dev
	podman build . -f dev.dockerfile -t amuman-cli
	podman run --rm -it --replace --tz local --pull newer \
		--name amuman-cli \
		--network amuman-dev \
		-v ./..:/app \
		-v ./../mock_nas:/shared \
		-w /app/cli \
		amuman-cli {{cmd}}