dev cmd="None":
	podman network create --ignore amuman-dev
	podman build . -f dev.dockerfile -t amuman-cli
	podman run --rm -it \
		--name amuman-cli \
		--network amuman-dev \
		-v ./..:/app \
		-v ./../mock_nas:/mnt/smb \
		-w /app/cli \
		--env-file ../.env \
		amuman-cli {{cmd}}