# Generated by Django 5.0 on 2024-01-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=500)),
                ("node_name", models.CharField(blank=True, max_length=100, null=True)),
                ("port", models.IntegerField(blank=True, null=True)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("error_time", models.DateTimeField(blank=True, null=True)),
                ("priority", models.IntegerField(default=0)),
                ("status", models.CharField(default="waiting", max_length=50)),
            ],
        ),
    ]
