# Generated by Django 4.2.9 on 2024-01-28 20:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Nodes",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("ip", models.CharField(max_length=15, unique=True)),
                (
                    "name",
                    models.CharField(blank=True, max_length=15, null=True, unique=True),
                ),
                ("port", models.IntegerField(blank=True, null=True)),
                (
                    "number_of_gpus",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("gpu_info", models.TextField(blank=True, null=True)),
                ("status", models.CharField(default="free", max_length=10)),
                (
                    "last_seen",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("user", models.CharField(blank=True, max_length=100, null=True)),
                ("path", models.TextField()),
                ("node_name", models.CharField(blank=True, max_length=100, null=True)),
                ("port", models.IntegerField(blank=True, null=True)),
                ("submit_time", models.DateTimeField(blank=True, null=True)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("error_time", models.DateTimeField(blank=True, null=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("slow", "Slow"),
                            ("normal", "Normal"),
                            ("fast", "Fast"),
                        ],
                        default="normal",
                        max_length=6,
                    ),
                ),
                (
                    "gpu_partition",
                    models.CharField(
                        choices=[
                            ("slow", "Slow"),
                            ("normal", "Normal"),
                            ("fast", "Fast"),
                        ],
                        default="normal",
                        max_length=6,
                    ),
                ),
                ("est", models.DurationField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Waiting", "Waiting"),
                            ("Pending", "Pending"),
                            ("Running", "Running"),
                            ("Finished", "Finished"),
                            ("Interrupted", "Interrupted"),
                        ],
                        default="Free",
                        max_length=50,
                    ),
                ),
                (
                    "assigned_node_id",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "assigned_gpu_id",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Gpus",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("gpu_uuid", models.TextField(blank=True, null=True, unique=True)),
                ("brand_name", models.TextField(blank=True, null=True)),
                ("gpu_speed", models.TextField(blank=True, null=True)),
                ("gpu_util", models.TextField(blank=True, null=True)),
                ("is_running_amumax", models.TextField(blank=True, null=True)),
                ("gpu_info", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Free", "Free"),
                            ("Running", "Running"),
                            ("Reserved", "Reserved"),
                            ("Unavailable", "Unavailable"),
                        ],
                        default="Free",
                        max_length=50,
                    ),
                ),
                (
                    "last_update",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "node_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common_models.nodes",
                    ),
                ),
                (
                    "task_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gpu_tasks",
                        to="common_models.task",
                    ),
                ),
            ],
        ),
    ]
