# Generated by Django 5.0 on 2024-01-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common_models", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="submit_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="user",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
