# Generated by Django 4.2.9 on 2024-01-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common_models", "0002_alter_gpus_status_alter_nodes_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="est",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
