# Generated by Django 4.2.9 on 2024-01-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common_models", "0003_alter_task_est"),
    ]

    operations = [
        migrations.AddField(
            model_name="gpus",
            name="no",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="gpu_partition",
            field=models.CharField(
                choices=[("Slow", "Slow"), ("Normal", "Normal"), ("Fast", "Fast")],
                default="normal",
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("Slow", "Slow"), ("Normal", "Normal"), ("Fast", "Fast")],
                default="normal",
                max_length=6,
            ),
        ),
    ]
