# Generated by Django 4.2.9 on 2024-01-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common_models", "0004_gpus_no_alter_task_gpu_partition_alter_task_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
