# Generated by Django 4.2.9 on 2024-01-25 13:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("common_models", "0004_nodes_number_of_gpus"),
    ]

    operations = [
        migrations.AddField(
            model_name="gpus",
            name="last_update",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
