# Generated by Django 4.2.9 on 2024-01-29 21:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common_models", "0005_alter_task_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="error",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="output",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
