# Generated by Django 4.2.9 on 2024-01-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common_models", "0005_gpus_last_update"),
    ]

    operations = [
        migrations.AddField(
            model_name="gpus",
            name="gpu_util",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gpus",
            name="is_running_amumax",
            field=models.TextField(blank=True, null=True),
        ),
    ]
