# Generated by Django 4.2.9 on 2024-01-29 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common_models", "0006_task_error_task_output"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="output",
            field=models.TextField(blank=True, null=True),
        ),
    ]
