# Generated by Django 4.2.9 on 2024-01-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common_models", "0006_gpus_gpu_util_gpus_is_running_amumax"),
    ]

    operations = [
        migrations.AddField(
            model_name="gpus",
            name="gpu_id",
            field=models.CharField(default=0, max_length=2, unique=True),
        ),
    ]
