# Generated by Django 4.2.9 on 2024-01-29 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common_models", "0007_alter_task_error_alter_task_output"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="flags",
            field=models.TextField(blank=True, null=True),
        ),
    ]
