# Generated by Django 4.2.9 on 2024-01-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common_models", "0008_rename_nodeid_gpus_node_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="est",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="gpu_partition",
            field=models.CharField(
                blank=True, default="normal", max_length=15, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
