# Generated by Django 4.2.9 on 2024-01-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common_models", "0009_task_est_task_gpu_partition_alter_task_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="est",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
