# Generated by Django 4.2.9 on 2024-01-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common_models", "0010_alter_task_est"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="assigned_gpu",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="assigned_node",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
