# Generated by Django 4.2.9 on 2024-01-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common_models", "0011_task_assigned_gpu_task_assigned_node"),
    ]

    operations = [
        migrations.AddField(
            model_name="gpus",
            name="task_id",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="gpus",
            name="gpu_id",
            field=models.CharField(default="", max_length=2, unique=True),
        ),
    ]
