# Generated by Django 4.2.9 on 2024-01-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common_models", "0012_gpus_task_id_alter_gpus_gpu_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="gpu_id",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
