# Generated by Django 4.2.9 on 2024-01-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "common_models",
            "0014_remove_gpus_gpu_id_remove_task_gpu_id_alter_gpus_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="gpus",
            name="gpu_uuid",
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
