# Generated by Django 4.2.9 on 2024-01-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common_models", "0015_gpus_gpu_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="gpu_partition",
            field=models.CharField(
                blank=True, default="normal", max_length=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
