# Generated by Django 4.2.9 on 2024-01-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common_models", "0016_alter_task_gpu_partition_alter_task_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="path",
            field=models.TextField(),
        ),
    ]
