# Generated by Django 4.2.9 on 2024-01-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common_models", "0017_alter_task_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("slow", "Slow"), ("normal", "Normal"), ("fast", "Fast")],
                default="normal",
                max_length=6,
            ),
        ),
    ]
