# Generated by Django 5.0 on 2024-01-25 09:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("master", "0003_delete_task"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nodes",
            name="is_active",
        ),
        migrations.AddField(
            model_name="nodes",
            name="last_seen",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AddField(
            model_name="nodes",
            name="status",
            field=models.CharField(default="free", max_length=10),
        ),
        migrations.AlterField(
            model_name="nodes",
            name="gpu_info",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nodes",
            name="ip",
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name="nodes",
            name="port",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
