# Generated by Django 4.2.9 on 2024-01-25 11:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("master", "0005_nodes_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Nodes",
        ),
    ]
