dev cmd="bash":
	podman network ls | grep amuman-dev || podman network create amuman-dev
	podman build . -f dev.dockerfile -t amuman-node-dev
	podman run --rm -it \
		--name amuman-node-dev \
		--network amuman-dev \
		-v ./..:/app \
		-v ./../mock_nas:/mnt/smb \
		-w /app/node \
		--device=nvidia.com/gpu=all \
		-p 5679:5679 \
		-e MANAGER_URL=amuman-manager-dev:8000 \
		-e NODE_NAME=test_node  \
		--env-file ../.env \
		amuman-node-dev {{cmd}}

staging:
	podman build . -t amuman-node-staging
	podman run --rm -it \
		--name amuman-node-staging \
		--network amuman-dev \
		--gpus all \
		--env-file ../.env \
		--cap-add SYS_ADMIN \
		--cap-add DAC_READ_SEARCH \
		amuman-node-staging
