# Generated by Django 5.0 on 2024-01-23 22:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Nodes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.CharField(max_length=15)),
                ("port", models.CharField(max_length=5)),
                ("gpu_info", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
