# Generated by Django 5.0 on 2024-01-24 18:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0002_nodes"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Task",
        ),
    ]
